//! Daemon-free manifest reconciliation operations shared between CLI and the
//! desktop app. Each function operates on the host filesystem only — no daemon
//! RPC — and takes an already-resolved `name: &str` so callers can handle
//! name-sanitisation however they like (e.g. the CLI uses `name::sanitize`;
//! the Tauri app can do the same without pulling in CLI crates).

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::manifest::{diff, store, DriftState, Manifest, Normalized};
use crate::paths::Paths;

/// Load `izba.yml` from a workspace dir, returning `(manifest, raw_yaml,
/// dockerfile_contents)`. `dockerfile` is `Some` only for a `build:` spec.
pub fn load_repo_manifest(dir: &Path) -> Result<(Manifest, String, Option<String>)> {
    let path = dir.join("izba.yml");
    let raw =
        std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    let m = Manifest::load_str(&raw)?;
    let dockerfile = match &m.spec.build {
        Some(b) => {
            let ctx = dir.join(b.context.as_deref().unwrap_or("."));
            let df = ctx.join(b.dockerfile.as_deref().unwrap_or("Dockerfile"));
            Some(
                std::fs::read_to_string(&df)
                    .with_context(|| format!("reading {}", df.display()))?,
            )
        }
        None => None,
    };
    Ok((m, raw, dockerfile))
}

/// Read the managed truth (config.json + policy.yaml) for `name` into a
/// `Normalized`, directly from disk (works on a stopped sandbox).
pub fn managed_normalized(paths: &Paths, name: &str) -> Result<Normalized> {
    use crate::daemon::egress::config::EgressPolicyConfig;
    use crate::state::{load_json, SandboxConfig, CONFIG_FILE};
    let dir = paths.sandbox_dir(name);
    let cfg: SandboxConfig =
        load_json(&dir.join(CONFIG_FILE))?.with_context(|| format!("no such sandbox: {name}"))?;
    let egress = EgressPolicyConfig::load(&dir)?.unwrap_or_default();
    Ok(Normalized::from_managed(name, &cfg, &egress))
}

/// Compute the structural diff between `izba.yml` in `dir` and the managed
/// truth for `name`. Returns `(state, deltas, review_token)` where the review
/// token binds the human review to the exact manifest + Dockerfile bytes.
/// Callers are responsible for persisting the token (see [`store::write_review`]).
pub fn compute_diff(
    paths: &Paths,
    dir: &Path,
    name: &str,
) -> Result<(DriftState, Vec<diff::FieldDelta>, String)> {
    let (m, raw, dockerfile) = load_repo_manifest(dir)?;
    let repo = Normalized::from_manifest(&m, name)?;
    let managed = managed_normalized(paths, name)?;
    let sandbox_dir = paths.sandbox_dir(name);
    let base = store::read_base(&sandbox_dir)?
        .map(|bm| Normalized::from_manifest(&bm, name))
        .transpose()?
        .unwrap_or_else(|| managed.clone());
    let state = super::classify(&base, &repo, &managed);
    let deltas = super::diff_normalized(&managed, &repo);
    let token = store::review_token(&raw, dockerfile.as_deref());
    Ok((state, deltas, token))
}

/// Write the managed truth for `name` back into `dir/izba.yml`, advance the
/// base, and clear the review token. Returns the path written.
/// Inverse of promote; no review gate (the caller is the human operator).
pub fn export(paths: &Paths, dir: &Path, name: &str) -> Result<PathBuf> {
    let managed = managed_normalized(paths, name)?;
    let manifest = managed.to_manifest();
    let path = dir.join("izba.yml");
    std::fs::write(&path, manifest_with_header(&manifest))
        .with_context(|| format!("writing {}", path.display()))?;
    let sandbox_dir = paths.sandbox_dir(name);
    store::write_base(&sandbox_dir, &manifest)?;
    store::clear_review(&sandbox_dir)?;
    Ok(path)
}

/// Prepend the managed-export header to a YAML manifest string.
pub fn manifest_with_header(m: &Manifest) -> String {
    format!(
        "# Generated by `izba export` — edit and `izba diff`/`izba promote` to apply.\n{}",
        m.to_yaml()
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::paths::Paths;

    const MINIMAL_MANIFEST: &str = concat!(
        "apiVersion: izba.dev/v1alpha1\n",
        "kind: Sandbox\n",
        "spec:\n",
        "  image: ubuntu:24.04\n",
        "  resources: { cpus: 1, memory: 1Gi }\n",
        "  rootDisk: { size: 1Gi }\n",
    );

    #[test]
    fn load_repo_manifest_reads_izba_yml() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("izba.yml"), MINIMAL_MANIFEST).unwrap();
        let (m, raw, dockerfile) = load_repo_manifest(tmp.path()).unwrap();
        assert_eq!(m.spec.resources.cpus, 1);
        assert!(raw.contains("ubuntu:24.04"));
        assert!(dockerfile.is_none());
    }

    #[test]
    fn load_repo_manifest_missing_returns_error() {
        let tmp = tempfile::tempdir().unwrap();
        assert!(load_repo_manifest(tmp.path()).is_err());
    }

    #[test]
    fn manifest_with_header_prepends_comment() {
        let m = Manifest::load_str(MINIMAL_MANIFEST).unwrap();
        let s = manifest_with_header(&m);
        assert!(s.starts_with("# Generated by `izba export`"), "got: {s}");
        assert!(s.contains("apiVersion: izba.dev/v1alpha1"));
    }

    #[test]
    fn managed_normalized_reads_config_json() {
        use crate::state::SandboxConfig;

        let tmp = tempfile::tempdir().unwrap();
        let paths = Paths::with_root(tmp.path().join("izba"));
        let name = "testbox";
        let sandbox_dir = paths.sandbox_dir(name);
        std::fs::create_dir_all(&sandbox_dir).unwrap();

        let cfg = SandboxConfig {
            image_digest: "sha256:abc".into(),
            image_ref: "ubuntu:22.04".into(),
            cpus: 4,
            mem_mb: 2048,
            workspace: "/workspace".into(),
            ports: vec![],
            volumes: vec![],
            builder: false,
        };
        std::fs::write(
            sandbox_dir.join(crate::state::CONFIG_FILE),
            serde_json::to_string(&cfg).unwrap(),
        )
        .unwrap();

        let n = managed_normalized(&paths, name).unwrap();
        assert_eq!(n.name, name);
        assert_eq!(n.cpus, 4);
        assert_eq!(n.mem_mb, 2048);
        match &n.image {
            crate::manifest::normalize::ImageSource::Ref(r) => assert_eq!(r, "ubuntu:22.04"),
            _ => panic!("expected Ref image source"),
        }
    }
}
