#!/usr/bin/env bash
# hack/mutants-issue.sh — upsert the single "mutation-gaps" tracking issue.
#
# The body is regenerated from ground truth each run (currently-surviving
# mutants only); killed mutants simply disappear next run. No checkmark state to
# reconcile. Requires `gh` authenticated with issues:write.
#
# Usage: hack/mutants-issue.sh <body-file>
set -euo pipefail
BODY_FILE="${1:?usage: mutants-issue.sh <body-file>}"
LABEL="mutation-gaps"
TITLE="Mutation testing gaps (surviving mutants)"

# Ensure the label exists (idempotent).
gh label create "$LABEL" --color B60205 --description "cargo-mutants survivors worklist" 2>/dev/null || true

# Prepend a generated-by header so readers know it is auto-maintained.
HEADER="_Auto-generated by the weekly mutation run (\`.github/workflows/mutants.yml\`). Regenerated from ground truth each run — do not edit by hand. See \`docs/quality/mutation-gaps-runbook.md\`._\n\n"
TMP="$(mktemp)"
printf "%b" "$HEADER" > "$TMP"
cat "$BODY_FILE" >> "$TMP"

EXISTING="$(gh issue list --label "$LABEL" --state open --json number --jq '.[0].number' || true)"
if [[ -n "${EXISTING:-}" && "$EXISTING" != "null" ]]; then
  gh issue edit "$EXISTING" --body-file "$TMP"
  echo "Updated issue #$EXISTING"
else
  gh issue create --title "$TITLE" --label "$LABEL" --body-file "$TMP"
  echo "Created tracking issue"
fi
