//! `izba export` — write the managed truth back into izba.yml (the human then
//! commits the git diff). Inverse of promote; no review gate (the human runs it).

use std::path::Path;

use anyhow::{Context, Result};
use izba_core::manifest::{store, Manifest};
use izba_core::paths::Paths;

pub fn run(paths: &Paths, dir: &Path, name_override: Option<&str>) -> Result<i32> {
    let default_name = super::workspace_default_name(dir)?;
    // Prefer an explicit name; else the existing manifest's name; else the dir.
    let name = match name_override {
        Some(n) => n.to_string(),
        None => match super::load_repo_manifest(dir) {
            Ok((m, _, _)) => m.metadata.name.unwrap_or(default_name),
            Err(_) => default_name,
        },
    };
    let managed = super::managed_normalized(paths, &name)?;
    let manifest = managed.to_manifest();
    let path = dir.join("izba.yml");
    std::fs::write(&path, manifest_with_header(&manifest))
        .with_context(|| format!("writing {}", path.display()))?;
    // The repo now equals managed -> advance base so diff reads in-sync.
    store::write_base(&paths.sandbox_dir(&name), &manifest)?;
    store::clear_review(&paths.sandbox_dir(&name))?;
    println!("exported managed truth -> {}", path.display());
    Ok(0)
}

pub(crate) fn manifest_with_header(m: &Manifest) -> String {
    format!(
        "# Generated by `izba export` — edit and `izba diff`/`izba promote` to apply.\n{}",
        m.to_yaml()
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use izba_core::manifest::Manifest;

    #[test]
    fn export_prepends_managed_header() {
        let m = Manifest::load_str(
            "apiVersion: izba.dev/v1alpha1\nkind: Sandbox\nspec:\n  image: ubuntu:24.04\n  resources: { cpus: 1, memory: 1Gi }\n  rootDisk: { size: 1Gi }\n",
        ).unwrap();
        let s = manifest_with_header(&m);
        assert!(s.starts_with("# Generated by `izba export`"), "got: {s}");
        assert!(s.contains("apiVersion: izba.dev/v1alpha1"));
    }
}
