name: Artifacts

on:
  push:
    branches: [main]
    paths:
      - 'hack/**'
      - 'crates/izba-init/**'
      - 'crates/izba-cli/**'
      - 'crates/izba-core/**'
      - 'crates/izba-proto/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/artifacts.yml'
      - '.github/workflows/_artifacts.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_artifacts.yml
